# Plualsight - Tensor and variabels
### Tensors
https://app.pluralsight.com/course-player?clipId=4878687b-5c52-4be5-9a2c-f2586c15898a

### Import packages

In [ ]:
import tensorflow as tf
import numpy as np
## Hest
tf.debugging.set_log_device_placement(True)

In [ ]:
tf.executing_eagerly()

True

In [ ]:
x0 = tf.constant(3)
x0

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
x0.shape

TensorShape([])

In [ ]:
x0.dtype

tf.int32

In [ ]:
x0.numpy()

3

In [ ]:
result0 = x0 + 5
result0

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
x1 = tf.constant([1.1, 2.2, 3.3, 4.4])
x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

### Add two tensors

In [ ]:
result1 = x1 + 5
result1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [ ]:
result1 = tf.add(x1, tf.constant(5.0))
result1

Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [ ]:
x2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
x2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [ ]:
x2 = tf.cast(x2, tf.float32)
x2

Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [ ]:
result3 = tf.multiply(x1, x2)
result3

Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [ ]:
arr_x1 = x1.numpy()
arr_x1

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [ ]:
arr_x4 = np.array([[10, 20],
                    [30, 40],
                    [50,60]])
arr_x4

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
x4 = tf.convert_to_tensor(arr_x4)
x4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

In [ ]:
tf.is_tensor(arr_x4)

False

### Variabels

In [ ]:
v1 = tf.Variable([1.5, 2, 5], [2, 6, 8])
v1

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1.5, 2. , 5. ], dtype=float32)>

In [ ]:
v2 = tf.Variable([[1.5, 2, 5], [2, 6, 8]], dtype=tf.float32)
v2

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [ ]:
tf.add(v1,v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3. ,  4. , 10. ],
       [ 3.5,  8. , 13. ]], dtype=float32)>