# 01 Tensorflow introduction
## TensorFlow 2 quickstart for beginners

pip install tensorflow



## Import Tensorflow

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\mikch\\anaconda3\\envs\\ml_trading\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


## Load a dataset

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
type(x_train)

numpy.ndarray

In [5]:
x_train.shape

(60000, 28, 28)

## Build a machine learning model
Build a tf.keras.Sequential model by stacking layers.

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 28, 28),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'flatten_input'}},
  {'class_name': 'Flatten',
   'config': {'name': 'flatten',
    'trainable': True,
    'batch_input_shape': (None, 28, 28),
    'dtype': 'float32',
    'data_format': 'channels_last'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'units': 128,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dropout',
   'config': {'name': 'dropout',
    'trainable': True,
    'dtype': 'float32',
    'rate': 

For each example, the model returns a vector of logits or log-odds scores, one for each class.

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.3625062 ,  0.31570056, -0.45602787,  0.67196316, -0.13664111,
         0.33569306, -0.22427106, -0.29502004,  0.43438148, -0.25206405]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.12455985, 0.11886409, 0.05494059, 0.16973583, 0.07561382,
        0.12126439, 0.0692698 , 0.06453838, 0.13384221, 0.06737109]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.1097822

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Train and evaluate your model
Use the Model.fit method to adjust your model parameters and minimize the loss:

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2938 - accuracy: 0.9153
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1429 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1087 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0886 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0756 - accuracy: 0.9762


The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0769 - accuracy: 0.9767


[0.07692280411720276, 0.9767000079154968]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.01455677e-07, 1.03376170e-08, 6.80433222e-05, 2.43756990e-03,
        1.21767985e-10, 3.90149125e-06, 1.36947756e-12, 9.97471690e-01,
        6.77409844e-06, 1.18925755e-05],
       [1.04282248e-04, 1.17981408e-05, 9.99760568e-01, 4.27217456e-05,
        1.41476882e-16, 1.22721849e-05, 5.25082651e-05, 7.68394070e-14,
        1.57919185e-05, 2.19582273e-12],
       [1.84563999e-06, 9.96749401e-01, 4.43141442e-04, 5.57833555e-05,
        3.39088037e-05, 1.73339777e-05, 8.78323772e-05, 2.19063275e-03,
        4.18871059e-04, 1.40145335e-06],
       [9.99939084e-01, 9.87478987e-09, 3.28183451e-05, 5.28358086e-08,
        6.52062852e-07, 4.48318042e-06, 1.08895119e-05, 4.93179959e-06,
        3.40887908e-07, 6.91753849e-06],
       [7.46933165e-06, 4.61853993e-11, 8.33430295e-06, 8.85492568e-09,
        9.96813715e-01, 8.24491053e-07, 2.45848587e-05, 2.60750039e-05,
        8.28993052e-07, 3.11826007e-03]], dtype=float32)>