# 01 Tensorflow introduction
## TensorFlow 2 quickstart for beginners

pip install tensorflow



## Import Tensorflow

In [33]:
import tensorflow as tf
import numpy as np

In [34]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\mikch\\anaconda3\\envs\\ml_trading\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


## Load a dataset

In [35]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

## Build a machine learning model
Build a tf.keras.Sequential model by stacking layers.

In [36]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [37]:
model.get_config()

{'name': 'sequential_2',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 28, 28),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'flatten_1_input'}},
  {'class_name': 'Flatten',
   'config': {'name': 'flatten_1',
    'trainable': True,
    'batch_input_shape': (None, 28, 28),
    'dtype': 'float32',
    'data_format': 'channels_last'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_2',
    'trainable': True,
    'dtype': 'float32',
    'units': 128,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dropout',
   'config': {'name': 'dropout_1',
    'trainable': True,
    'dtype': 'float32',
  

For each example, the model returns a vector of logits or log-odds scores, one for each class.

In [38]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.09486081,  0.3123238 ,  0.13221559,  0.5559108 ,  0.3164674 ,
         0.5990117 , -0.55985403, -0.3630237 ,  0.02790846, -0.58484155]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:

In [39]:
tf.nn.softmax(predictions).numpy()

array([[0.09648228, 0.11991972, 0.10015453, 0.15299565, 0.12041764,
        0.15973407, 0.05013125, 0.06103668, 0.09023407, 0.04889412]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.

In [40]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [41]:
loss_fn(y_train[:1], predictions).numpy()

1.8342448

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [42]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Train and evaluate your model
Use the Model.fit method to adjust your model parameters and minimize the loss:

In [43]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2955 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1444 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1091 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0893 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0745 - accuracy: 0.9761


The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

In [44]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0697 - accuracy: 0.9783


[0.06971266120672226, 0.9782999753952026]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [45]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [46]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.2847617e-08, 4.5651994e-08, 1.1982923e-05, 6.0980485e-05,
        3.6984658e-11, 7.6650008e-07, 2.4931096e-13, 9.9992502e-01,
        1.6626173e-07, 1.0552643e-06],
       [6.9996595e-09, 9.1603164e-05, 9.9988413e-01, 1.4320101e-05,
        2.3067427e-12, 8.1964172e-06, 2.0772730e-07, 3.7206401e-13,
        1.4544188e-06, 1.5572253e-12],
       [1.0453084e-07, 9.9923754e-01, 1.4134670e-04, 4.9685664e-06,
        5.9633967e-05, 1.0133091e-05, 1.4809482e-05, 4.8044839e-04,
        4.9953607e-05, 1.0470889e-06],
       [9.9766695e-01, 2.9360399e-07, 1.3191576e-04, 3.6195004e-07,
        4.1918287e-05, 2.7083042e-05, 2.8734765e-04, 6.7096669e-04,
        4.1607385e-07, 1.1729161e-03],
       [3.5530596e-07, 2.0503478e-08, 5.8217876e-05, 1.8676654e-07,
        9.9839896e-01, 5.9567810e-06, 2.5488273e-06, 1.1531560e-04,
        8.8888904e-05, 1.3295751e-03]], dtype=float32)>